# Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: "Bijira Documentation"
site_description: Bijira Documentation
site_author: WSO2
site_url: https://wso2.com/bijira/docs

# Repository
repo_name: wso2/docs-bijira
repo_url: https://github.com/wso2/docs-bijira
edit_uri: https://github.com/wso2/docs-bijira/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: Â©2025 WSO2 LLC.

# Configuration
watch:
  - theme/
  - docs/assets/

theme:
  name: material
  custom_dir: theme/material
  logo: assets/images/BijiraDocs.svg
  logo_light: assets/images/BijiraDocsWhite.svg
  font:
    text: Montserrat
  favicon: assets/images/favicon.png
  features:
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: "en"
  palette:
    # Palette toggle for light mode
       - media: "(prefers-color-scheme: light)"
         scheme: default 
         toggle:
          icon: assets/libs/oxygen-ui-icons/1.7.3/crescent-bright-16.svg
          name: Switch to dark mode
      # Palette toggle for dark mode
       - media: "(prefers-color-scheme: dark)"
         scheme: slate
         toggle:
           icon: assets/libs/oxygen-ui-icons/1.7.3/sun-16.svg
           name: Switch to light mode

  icon:
    logo: logo
#Breaks build if there's a warning
strict: false
# Navigation
nav:
  - Home: index.md
  - Introduction:
      - What is Bijira?: introduction/what-is-bijira.md
      - Quick Start Guide: introduction/quick-start-guide.md
      - Bijira Concepts:
        # - Resource Hierarchy: resource-hierarchy.md
        - Organization: bijira-concepts/organization.md
        - Project: bijira-concepts/project.md
        # - Deployment Tracks: bijira-concepts/deployment-tracks.md
        - Data Planes: bijira-concepts/data-planes.md
  - Create API Proxy:
      - Overview: create-api-proxy/overview.md
      - My APIs (Ingress):
          - REST APIs:
              - Create with GenAI: create-api-proxy/my-apis/http/create-with-genai.md
              - Import API Contract: create-api-proxy/my-apis/http/import-api-contract.md
              - Import API Contract from GitHub: create-api-proxy/my-apis/http/import-api-from-github.md
              - Start with Endpoint: create-api-proxy/my-apis/http/start-with-endpoint.md
              - Start from Scratch: create-api-proxy/my-apis/http/start-from-scratch.md
          - WebSocket APIs:
              - Create with GenAI: create-api-proxy/my-apis/websocket/create-with-genai.md
              - Import API Contract: create-api-proxy/my-apis/websocket/import-api-contract.md
              - Start with Endpoint: create-api-proxy/my-apis/websocket/start-with-endpoint.md
              - Start from Scratch: create-api-proxy/my-apis/websocket/start-from-scratch.md
              - Limitations: create-api-proxy/my-apis/websocket/quotas-and-limitations.md
          - GraphQL APIs:
              - Import API Contract: create-api-proxy/my-apis/graphql/import-api-contract.md
              - Start with Endpoint: create-api-proxy/my-apis/graphql/start-with-endpoint.md
      - Third Party APIs (Egress):
          - AI APIs:
              - Overview: create-api-proxy/third-party-apis/ai-apis.md
              - Providers:
                  - OpenAI: create-api-proxy/third-party-apis/open-ai.md
                  - Azure OpenAI: create-api-proxy/third-party-apis/azure-ai.md
                  - Mistral: create-api-proxy/third-party-apis/mistral.md
                  - AWS Bedrock: create-api-proxy/third-party-apis/awsbedrock.md
                  - Anthropic: create-api-proxy/third-party-apis/claude.md
              - Policies:
                  - Token-Based Rate Limit: create-api-proxy/third-party-apis/token-ratelimit.md
                  - Guardrails:
                      - Overview: create-api-proxy/third-party-apis/guardrails.md
                      # - Basic Guardrails:
                      - Regex Guardrail: create-api-proxy/third-party-apis/guardrails/basic-guardrails/regex-guardrail.md
                      - Word Count Guardrail: create-api-proxy/third-party-apis/guardrails/basic-guardrails/word-count-guardrail.md
                      - Sentence Count Guardrail: create-api-proxy/third-party-apis/guardrails/basic-guardrails/sentence-count-guardrail.md
                      - Content Length Guardrail: create-api-proxy/third-party-apis/guardrails/basic-guardrails/content-length-guardrail.md
                      - URL Guardrail: create-api-proxy/third-party-apis/guardrails/basic-guardrails/url-guardrail.md
                      - Regex PII Masking: create-api-proxy/third-party-apis/guardrails/basic-guardrails/regex-pii-masking.md
                      # - Advanced Guardrails:
                      - PII Masking: create-api-proxy/third-party-apis/guardrails/advanced-guardrails/pii-masking.md
                      # - Third Party Guardrail Integrations:
                      - Azure Content Safety Content Moderation: create-api-proxy/third-party-apis/guardrails/third-party-guardrail-integrations/azure-content-safety-content-moderation.md
                      - AWS Bedrock Guardrail: create-api-proxy/third-party-apis/guardrails/third-party-guardrail-integrations/aws-bedrock-guardrail.md
                  - Semantic Cache: create-api-proxy/third-party-apis//semantic-cache.md
          - Get from Marketplace: create-api-proxy/third-party-apis/get-from-marketplace.md
          - Import API Contract: create-api-proxy/third-party-apis/import-api-contract.md
  - Develop API Proxy:
      - Authentication and Authorization:
          - Secure API Access with Asgardeo: develop-api-proxy/authentication-and-authorization/secure-api-access-with-asgardeo.md
          - Secure API Access with Bijira STS: develop-api-proxy/authentication-and-authorization/secure-api-access-with-bijira-sts.md
          - Secure API Access with Azure AD: develop-api-proxy/authentication-and-authorization/secure-api-access-with-azure-ad.md
          - Secure API Access with an External Key Manager: develop-api-proxy/authentication-and-authorization/secure-api-access-with-external-idp.md
          - Secure Communication Between the Bijira Gateway and Your Backend with OAuth2: develop-api-proxy/authentication-and-authorization/secure-communication-between-bijira-gateway-and-backend-with-oauth2.md
          - Secure Communication Between the Bijira Gateway and Your Backend with Mutual TLS: develop-api-proxy/authentication-and-authorization/secure-communication-between-the-bijira-gateway-and-your-backend-with-mutual-tls.md
      - Policy:
          - Overview: develop-api-proxy/policy/overview.md
          - Policies: develop-api-proxy/policy/policies.md
          - Attach and Manage Policies: develop-api-proxy/policy/attach-and-manage-policies.md
        # - Apply Advanced Settings on Mediation Policies: develop-api-proxy/policy/apply-advanced-settings-on-mediation-policies.md
      - Documents: develop-api-proxy/documents.md
      - Lifecycle: develop-api-proxy/lifecycle-management.md
      - Subscription Plans: develop-api-proxy/subscription-plans.md
  - Test API Proxy:
      - OpenAPI Console: test-api-proxy/openapi-console.md
      - WebSocket Console: test-api-proxy/ws-test-console.md
      - GraphQL Console: test-api-proxy/graphql-console.md
      - cURL: test-api-proxy/curl.md
      - API Chat: test-api-proxy/api-chat.md
  - MCP Servers:
      - Overview: mcp-servers/get-started-with-mcp.md
      - Design MCP Servers: mcp-servers/design-mcp-servers.md
      - Proxy Remote MCP Servers: mcp-servers/proxy-remote-servers.md
      - Customize Developer Portal as an MCP Hub: mcp-servers/devportal-mcp-hub.md
  - API Governance:
      - API Governance Overview: governance/overview.md
      - Govern API Proxy: governance/govern-api-proxy.md
  - AI Gateway:
      - Overview: ai-gateway/overview.md
      - AI Workspace:
          - Getting Started: ai-gateway/ai-workspace/getting-started.md
          - Setting Up: ai-gateway/ai-workspace/ai-gateways/setting-up.md
          - LLM Providers:
              - Overview: ai-gateway/ai-workspace/llm-providers/overview.md
              - Configure Provider: ai-gateway/ai-workspace/llm-providers/configure-provider.md
              - Manage Provider: ai-gateway/ai-workspace/llm-providers/manage-provider.md
          - LLM Proxies:
              - Overview: ai-gateway/ai-workspace/llm-proxies/overview.md
              - Configure Proxy: ai-gateway/ai-workspace/llm-proxies/configure-proxy.md
              - Manage Proxy: ai-gateway/ai-workspace/llm-proxies/manage-proxy.md
#          - Insights: ai-gateway/ai-workspace/insights.md
          - Policies:
              - Overview: ai-gateway/ai-workspace/policies/overview.md
              - Token-Based Rate Limit: ai-gateway/ai-workspace/policies/token-based-rate-limit.md
              - Guardrails:
                  - Overview: ai-gateway/ai-workspace/policies/guardrails/overview.md
                  - Semantic Prompt Guard: ai-gateway/ai-workspace/policies/guardrails/semantic-prompt-guard.md
                  - PII Masking Regex: ai-gateway/ai-workspace/policies/guardrails/regex-pii-masking.md
                  - Azure Content Safety: ai-gateway/ai-workspace/policies/guardrails/azure-content-safety.md
                  - Semantic Cache: ai-gateway/ai-workspace/policies/guardrails/semantic-cache.md
              - Other Policies:
#                  - API Key Auth: ai-gateway/ai-workspace/policies/guardrails/api-key-auth.md
#                  - JWT Auth: ai-gateway/ai-workspace/policies/guardrails/jwt-auth.md
#                  - CORS: ai-gateway/ai-workspace/policies/guardrails/cors.md
                  - Rate Limit - Basic: ai-gateway/ai-workspace/policies/guardrails/basic-rate-limit.md
                  - Token Based Rate Limit: ai-gateway/ai-workspace/policies/guardrails/token-based-ratelimit.md
                  - Model Round Robin: ai-gateway/ai-workspace/policies/guardrails/model-round-robin.md
                  - Prompt Decorator: ai-gateway/ai-workspace/policies/guardrails/prompt-decorator.md
                  - Prompt Template: ai-gateway/ai-workspace/policies/guardrails/prompt-template.md
  - API Gateway:
      # - Overview: api-platform-gateway/overview.md
      # - Bijira Cloud Gateway: api-platform-gateway/cloud-gateway.md
      - Self-Hosted Gateway:
          - Getting Started: api-platform-gateway/getting-started.md
          - Setting Up: api-platform-gateway/setting-up.md
          - Adding and Managing Policies: api-platform-gateway/manage-policies.md
          # - Analytics: api-platform-gateway/analytics.md
          # - Troubleshooting: api-platform-gateway/troubleshooting.md
      - Third-Party Gateways:
          - Overview: federation/overview.md
          - Discover APIs from AWS API Gateway: federation/api-discovery-aws.md
  - Monitor and Insights:
      - Logs: 
        - Overview: monitoring-and-insights/logs/overview.md
        - Runtime Logs: monitoring-and-insights/logs/runtime-logs.md
        - Audit Logs: monitoring-and-insights/logs/audit-logs.md
      - Integrate Bijira with Moesif: monitoring-and-insights/integrate-bijira-with-moesif.md
  - Administer:
      - Create API Subscription Plans: administer/settings/create-api-subscription-plans.md
      - Configure a Custom Domain for Your Organization: administer/settings/configure-a-custom-domain-for-your-organization.md
      - Manage Environments: administer/manage-environments/manage-environments.md
      - Manage CD pipelines: administer/manage-cd-pipelines/manage-cd-pipelines.md
      - Configure External Key Manager:
        - Configure Asgardeo as an External Key Manager: administer/configure-an-external-idp/configure-asgardeo-as-an-external-idp.md
        - Configure Azure as an External Key Manager: administer/configure-an-external-idp/configure-azure-ad-as-an-external-idp.md
        - Configure Custom External Key Manager: administer/configure-an-external-idp/configure-custom-external-idp.md
      - Configure Enterprise Login: administer/configure-enterprise-login/configure-enterprise-login.md
      - Configure VPNs on Bijira Cloud Data Plane: administer/configure-vpns/configure-vpns.md
  - Workflows:
      - Configure Workflow Approvals: workflows/configure-workflow-approvals.md
      - Submit Workflow Approval Requests: workflows/submit-workflow-requests.md
      - Review Workflow Approval Requests: workflows/review-workflows-requests.md
  - Tutorials:
      - Expose a Service as a Managed API: tutorials/expose-a-service-as-a-managed-api.md
      - Secure an API with RBAC: tutorials/secure-an-api-with-role-based-access-control.md
  - Bijira Samples:
      - Samples Overview: samples/samples-overview.md
  - Developer Portal:
      - Theming Developer Portal:
          - Theming with AI: devportal/theming-devportal-with-ai.md
          - Theming Manually:
              - Theme in Organizational Level: devportal/theming-devportal-org-level.md
              - Theme in API Level: devportal/theming-devportal-api-level.md
          - Devportal Mode: devportal/developer-portal-mode.md
      - Discover APIs:
          - Search APIs: devportal/discover-apis/api-search.md
          - Documentations: devportal/discover-apis/api-documentations.md
      - Consume an API:
          - Consume an API Secured with OAuth2: devportal/consuming-services/consume-an-api-secured-with-oauth2.md
          - Consume an API Secured with API Key: devportal/consuming-services/consume-an-api-secured-with-api-key.md
      - Manage Applications:
          - Create an Application: devportal/manage-applications/create-an-application.md
      - Manage Subscriptions:
          - Subscribe to an API: devportal/manage-subscriptions/subscribe-to-an-api.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list
plugins:
  - search
  - include-markdown
  - glightbox
  - open-in-new-tab
  - markdownextradata: {}
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
  - assets/lib/json-formatter/json-formatter.css
extra_javascript:
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wso2
  expanded_navs:
    - title: Introduction
      options:
        - verticle-line
    - title: Create API Proxy
      options:
        - verticle-line
        - divider
    - title: Tutorials
      options:
        - verticle-line-only
    - title: Develop API Proxy
      options:
        - verticle-line-only
    - title: Test API Proxy
      options:
        - verticle-line-only
    - title: MCP Servers
      options:
        - verticle-line-only
    - title: API Governance
      options:
        - verticle-line-only
    - title: Gateway Federation
      options:
        - verticle-line-only
    - title: Monitor and Insights
      options:
        - verticle-line-only
    - title: Administer
      options:
        - verticle-line-only
    - title: Workflows
      options:
        - verticle-line-only
    - title: Bijira Samples
      options:
        - verticle-line-only
    - title: Developer Portal
      options:
        - verticle-line
        - divider
  nav_icons:
    Home:
      icon: octicons/home-16
      level: 1
    Introduction:
      icon: octicons/info-16
      level: 1
    Bijira Samples:
      icon: octicons/file-code-16
      level: 1
    Tutorials:
      icon: octicons/mortar-board-16
      level: 1
    Create API Proxy:
      icon: octicons/pencil-16
      level: 1
    Develop API Proxy: 
      icon: octicons/tools-16
      level: 1
    Test API Proxy:
      icon: octicons/bug-16
      level: 1
    MCP Servers:
      icon: octicons/server-16
      level: 1
    API Governance:
      icon: octicons/shield-16
      level: 1
    AI Gateway:
      icon: octicons/cpu-16
      level: 1
    API Gateway:
      icon: octicons/globe-16
      level: 1
    Monitor and Insights:
      icon: octicons/graph-16
      level: 1
    Administer:
      icon: octicons/lock-16
      level: 1
    Workflows:
      icon: octicons/workflow-16
      level: 1
    Developer Portal:
      icon: octicons/book-16
      level: 1

#site_version: 1.0.0
# base_path: http://localhost:8000

